### PR TITLE
render_to_string fix

### PR DESCRIPTION
**Pull request by cbmike**
pass options only to the render_to_string_with_wicked_pdf

### CODE REVIEW

**Comment by unixmonkey** [comment]
Why is this desirable for you? This means if you call render with a block or arguments, they will now be ignored. Is this from a change in Rails internals or something?

File: lib/wicked_pdf/pdf_helper.rb [hunk 1]
```diff
@@ -22,7 +22,7 @@ def render(*args)
     def render_to_string(*args)
       options = args.first
       if options.is_a?(Hash) && options.key?(:pdf)
-        render_to_string_with_wicked_pdf(options, *args, &block)
```
[the remark this answers is not in the document]
Comment (mathieujobin) [reply lib/wicked_pdf/pdf_helper.rb:25]: method below does not take a 2nd arg... so this looks correct

**Review by mathieujobin — APPROVED** [review]
problem introduced in #925 

It appears this is missing some tests.
this should be part of next release

**Comment by KonstantinReido** [comment]
PDF generation in my project stopped work because of this issue. It happened after an update on 2.6.0 from 2.1.0.

`undefined local variable or method 'block'`

Will be good to see these changes in the next release.

**Comment by mathieujobin** [comment]
manual merge into master here 
`gem "wicked_pdf", github: 'mathieujobin/wicked_pdf', branch: 'pr-962'`

all tests passed - https://github.com/mathieujobin/wicked_pdf/actions/runs/2268571025

**Review by unixmonkey — APPROVED** [review]

**Comment by unixmonkey** [comment]
This has been released in version 2.6.2. Please let me know if you have any issues.
Thank you!
