### ISSUE TITLE
undefined local variable or method `block' for render_to_string

### ISSUE THREAD

**Issue by lefermierperso** [mileszs/wicked_pdf#1003]
## Issue description
`undefined local variable or method `block' for render_to_string in PdfHelper` with correct pdf option which worked on 2.1.0
it throw this error since i use the master version

I temporary fix it by calling "render_to_string_with_wicked_pdf" instead of render_to_string

## Expected or desired behavior
should be able to use render_to_string

## System specifications

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`):
  remote: git://github.com/mileszs/wicked_pdf.git
    wicked_pdf (2.1.0)
  wicked_pdf!

wkhtmltopdf version (output of `wkhtmltopdf --version`):
wkhtmltopdf 0.12.6 (with patched qt)

whtmltopdf [provider gem](https://rubygems.org/search?utf8=%E2%9C%93&query=wkhtmltopdf) and version if one is used:

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar):
Ubuntu 18.04

**Comment by unixmonkey** [comment]
Is this with Rails 7, or something else?

**Comment by hknaksu** [comment]
+1
this issue continues.. not fixed in 2.6.0.  Using Rails 5.2.7.1 w/ Ruby 2.6.9

**Comment by starrychloe** [comment]
Happens in Rails 5.2.7, Ruby 2.7.2
