### ISSUE TITLE
NameError (undefined local variable or method `possible_locations' for #<WickedPdf::Binary

### ISSUE THREAD

**Issue by QPierre1** [mileszs/wicked_pdf#1022]
Hi, I identify a problem with a variable definition. 

possible_locations is used here without being defined : 
https://github.com/mileszs/wicked_pdf/blob/2dc96dde2e0fd7362395064f2480cac1edcc1f48/lib/wicked_pdf/binary.rb#L48

I used this library during several years without meet this problem before.

Environnement :
ruby '3.1.2'
'rails', '6.1.5'

**Comment by jensFrerichs** [comment]
We have the same problem: 
```
undefined local variable or method `possible_locations' for #<WickedPdf::Binary:0x00007f3542a69130>
Did you mean?  possible_binary_locations
```

**Comment by olleolleolle** [comment]
Introduced in #816, I suspect it's just a rename away to fix this. I'll PR real quick, to show what I mean.

**Comment by unixmonkey** [comment]
This is now published in version 2.6.3 of the gem. Thank you all for reporting and fixing!
